# Generated by Django 5.0.9 on 2025-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
    ]
