# Generated by Django 5.0.9 on 2025-01-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0003_subcategorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('SKU', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioDescuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Stock', models.IntegerField()),
                ('StockMax', models.IntegerField()),
                ('StockMin', models.IntegerField()),
                ('CalificacionPromedio', models.IntegerField(default=0)),
                ('Vistas', models.IntegerField(default=0)),
                ('Estado', models.BooleanField(default=True)),
                ('FechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('Marca', models.CharField(max_length=100)),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descripcion', models.TextField()),
            ],
        ),
    ]
