# Generated by Django 5.0.9 on 2025-01-28 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0006_imagenesproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('IdFavoritos', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='Blyss.productos')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
