# Generated by Django 5.0.9 on 2025-01-28 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0007_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('IdCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField(default=1)),
                ('FechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='Blyss.productos')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
