# Generated by Django 5.0.9 on 2025-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0008_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriasproductos',
            name='Imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
