# Generated by Django 5.0.9 on 2025-01-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0009_categoriasproductos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriasproductos',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='categorias',
            name='Imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
