# Generated by Django 5.0.9 on 2025-02-04 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0011_bannercategorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHome',
            fields=[
                ('IdBannerHome', models.AutoField(primary_key=True, serialize=False)),
                ('Img', models.BinaryField()),
                ('Estado', models.BooleanField(default=True)),
                ('EsPrincipal', models.BooleanField(default=False)),
                ('FechaAgregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Home',
                'verbose_name_plural': 'Banners Home',
            },
        ),
    ]
