# Generated by Django 5.0.9 on 2025-02-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0012_bannerhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVistas',
            fields=[
                ('IdVista', models.AutoField(primary_key=True, serialize=False)),
                ('FechaVista', models.DateTimeField(auto_now_add=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blyss.productos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Vista',
                'verbose_name_plural': 'Historial de Vistas',
            },
        ),
    ]
