# Generated by Django 5.0.9 on 2025-02-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0013_historialvistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertasHome',
            fields=[
                ('IdOfertasHome', models.AutoField(primary_key=True, serialize=False)),
                ('EsPrincipal', models.BooleanField(default=False)),
                ('FechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_home', to='Blyss.productos')),
            ],
            options={
                'verbose_name': 'Oferta Home',
                'verbose_name_plural': 'Ofertas Home',
                'ordering': ['-FechaAgregado'],
            },
        ),
    ]
