# Generated by Django 5.0.9 on 2025-02-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0014_ofertashome'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannersItems',
            fields=[
                ('IdBannersItems', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=255)),
                ('FechaAgregada', models.DateTimeField(auto_now_add=True)),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_creados', to=settings.AUTH_USER_MODEL)),
                ('Producto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_producto1', to='Blyss.productos')),
                ('Producto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_producto2', to='Blyss.productos')),
                ('Producto3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_producto3', to='Blyss.productos')),
                ('Producto4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_producto4', to='Blyss.productos')),
            ],
        ),
    ]
