# Generated by Django 5.0.9 on 2025-02-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0015_bannersitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersitems',
            name='Imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
