# Generated by Django 5.0.9 on 2025-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0016_bannersitems_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerhome',
            name='Url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
