# Generated by Django 5.0.9 on 2025-02-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0019_pedido_pago_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='IdDirecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_envio', to='Blyss.direcciones'),
        ),
    ]
