# Generated by Django 5.0.9 on 2025-03-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blyss', '0021_remove_detallepedido_iddirecciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('IdPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('IdRol', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('IdUsuarioPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAsignado', models.DateTimeField(auto_now_add=True)),
                ('AsignadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_asignados_por', to=settings.AUTH_USER_MODEL)),
                ('Permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='Blyss.permisos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Permiso',
                'verbose_name_plural': 'Usuarios Permisos',
                'unique_together': {('Usuario', 'Permiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('IdUsuarioRol', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAsignado', models.DateTimeField(auto_now_add=True)),
                ('AsignadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados_por', to=settings.AUTH_USER_MODEL)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='Blyss.roles')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'verbose_name_plural': 'Usuarios Roles',
                'unique_together': {('Usuario', 'Rol')},
            },
        ),
    ]
